import React from "react"
import Loader from "react-loader-spinner"
import { useEthers } from "@usedapp/core"

import Head from "next/head"
import NavBar from "./NavBar"
import Link from "next/link"
import styles from "@Styles/Home.module.css"
import AccountButton from "./AccountModal"
import Login from "./login/Login"

const Layout = props => {
  const { account } = useEthers()

  return (
    <div className={styles.container}>
      <Head>
        <title>Communities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AccountButton />
      <main className={styles.main}>
        <div className={styles.header}>
          <Link href="/">
            <a>
              <h1 className={styles.title}>Communities</h1>
            </a>
          </Link>
          <NavBar />
        </div>

        {
          // loading?
          //     <Loader
          //         type="BallTriangle"
          //         style={{marginTop: '100px'}}
          //         // type="Puff"
          //         color="#00BFFF"
          //         height={150}
          //         width={150} //3 secs
          //     />
          //     :
          !account ? (
            <Login />
          ) : (
            <div className={styles.content}>{props.children}</div>
          )
        }
      </main>
    </div>
  )
}

export default Layout
